name: flutter_template
description: A new Flutter application.

publish_to: 'none'

version: 0.1.2+1002

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: "2.0.1"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0

flutter:
  generate: true
  uses-material-design: true
